image: nixos/unstable
oauth: pages.sr.ht/PAGES:RW
packages:
  - nixos.hut
  - nixos.python3
environment:
  site: tmayoff.srht.site
tasks:
  - pacakge: |
      python3 -m venv mkdocs
      . mkdocs/bin/activate
      python3 -m pip install --upgrade pip
      pip install mkdocs mkdocs-material mkdocs-mermaid2-plugin
      cd wren
      mkdocs build -d site
      tar -C site -czf ../site.tar.gz .
  
  - upload: |
      hut pages publish -s wren -d $site site.tar.gz

triggers:
  - action: email
    condition: failure
    to: Tyler Mayoff tyler@tylermayoff.com
    
