image: nixos/unstable
oauth: pages.sr.ht/PAGES:RW
packages:
  - nixos.hut
  - nixos.python3
environment:
  site: wren.srht.site
tasks:
  - pacakge: |
      python3 -m venv mkdocs
      . mkdocs/bin/activate
      python3 -m pip install --upgrade pip
      pip install mkdocs mkdocs-material mkdocs-mermaid2-plugin

      git clone git@git.sr.ht:~tmayoff/wren
      cd wren

  - upload: |
      hut pages publish -d $site site.tar.gz

triggers:
  - action: email
    condition: failure
    to: Tyler Mayoff tyler@tylermayoff.com
    
