image: nixos/unstable
environment:
  site: tmayoff.srht.site
  NIX_CONFIG: "experimental-features = nix-command flakes"
oauth: pages.sr.ht/PAGES:RW
tasks:
  - setup: mkdir -p wren/build/docs
  - build_docs: |
      cd wren
      nix develop --command just build_docs
  - upload: |
      cd wren
      tar -cvzf site.tar.gz -C build/docs/html .
      nix run nixpkgs#hut -- pages publish -d tmayoff.srht.site -s wren site.tar.gz
