name: docs
on:
  push:
    branches:
      - main
    paths:
      - docs/**
      - mkdocs.yml
  workflow_dispatch:
      
permissions:
  contents: write
jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v14
      - uses: DeterminateSystems/flake-checker-action@v9
      - uses: DeterminateSystems/magic-nix-cache-action@v8
     
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: build docs
        run: |
          mkdir build/docs
          nix develop --command just build_docs
      - name: upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/docs/html'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
